TAGS = [
    "cooking",
    "cleaning",
    "laundry",
    "dusting",
    "dishes",
    "ironing",
    "grocery",
    "other",
]

# Suggestions only — any city name is accepted; these seed the autocomplete.
CITIES = [
    # Bay Area
    "San Jose",
    "Santa Clara",
    "Sunnyvale",
    "Cupertino",
    "Milpitas",
    "Fremont",
    "Newark",
    "Union City",
    "Hayward",
    "San Leandro",
    "Castro Valley",
    "Mountain View",
    "Palo Alto",
    "East Palo Alto",
    "Los Altos",
    "Los Altos Hills",
    "Menlo Park",
    "Redwood City",
    "San Carlos",
    "Belmont",
    "Foster City",
    "San Mateo",
    "Burlingame",
    "Millbrae",
    "South San Francisco",
    "Daly City",
    "Pacifica",
    "San Bruno",
    "San Francisco",
    "Oakland",
    "Berkeley",
    "Emeryville",
    "Alameda",
    "Albany",
    "El Cerrito",
    "Richmond",
    "Piedmont",
    "Dublin",
    "Pleasanton",
    "Livermore",
    "San Ramon",
    "Danville",
    "Alamo",
    "Walnut Creek",
    "Concord",
    "Pleasant Hill",
    "Lafayette",
    "Orinda",
    "Moraga",
    "Martinez",
    "Antioch",
    "Pittsburg",
    "Brentwood",
    "Oakley",
    "Campbell",
    "Los Gatos",
    "Saratoga",
    "Morgan Hill",
    "Gilroy",
    "Santa Cruz",
    "Scotts Valley",
    "Watsonville",
    "Half Moon Bay",
    "Tracy",
    "Mountain House",
    "Manteca",
    "Stockton",
    "Modesto",
    "Vallejo",
    "Benicia",
    "Fairfield",
    "Vacaville",
    "Napa",
    "American Canyon",
    "Petaluma",
    "Novato",
    "San Rafael",
    "Mill Valley",
    "Sausalito",
    "Santa Rosa",
    "Rohnert Park",
    "Sonoma",
    # Rest of California
    "Sacramento",
    "Elk Grove",
    "Roseville",
    "Folsom",
    "Davis",
    "Fresno",
    "Clovis",
    "Bakersfield",
    "Los Angeles",
    "Long Beach",
    "Glendale",
    "Pasadena",
    "Burbank",
    "Santa Monica",
    "Torrance",
    "Irvine",
    "Anaheim",
    "Santa Ana",
    "Fullerton",
    "Orange",
    "Huntington Beach",
    "Newport Beach",
    "San Diego",
    "Chula Vista",
    "Carlsbad",
    "Oceanside",
    "Riverside",
    "Corona",
    "Ontario",
    "Rancho Cucamonga",
    "San Bernardino",
    "Temecula",
    "Ventura",
    "Oxnard",
    "Thousand Oaks",
    "Santa Barbara",
    "San Luis Obispo",
    "Monterey",
    "Salinas",
    "Redding",
    "Chico",
]

DAYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
TIMES = ["morning", "afternoon", "evening"]
START_TIMINGS = ["asap", "within_2_weeks", "within_month", "flexible"]
PAY_TYPES = ["hourly", "daily", "monthly", "one_time"]
CONNECTION_STATUSES = ["pending", "accepted", "declined"]
REPORT_REASONS = [
    "inappropriate_behavior",
    "harassment",
    "scam_or_fraud",
    "no_show",
    "fake_profile",
    "other",
]
ROLES = ["worker", "customer"]
LANGUAGES = ["en", "hi"]
MEDIA_KINDS = ["image", "video"]
